services:
  - type: web
    name: ai-search-backend
    env: python
    buildCommand: |
      pip install -r requirements.txt
      python manage.py migrate
    startCommand: gunicorn backend.config.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: backend.config.settings
      - key: SERPAPI_KEY
        value: false
      - key: YOUTUBE_API_KEY
        value: false
      - key: DEBUG
        value: false
      - key: ALLOWED_HOSTS
        value: .onrender.com
      - key: CORS_ALLOWED_ORIGINS
        value: https://your-netlify-domain.netlify.app
      - key: SECRET_KEY
        value: your-secret-key-here