services:
  - type: web
    name: ai-search-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn backend.backend.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: backend.settings
      - key: SERPAPI_KEY
        value: false
      - key: YOUTUBE_API_KEY
        value: false