services:
  - type: web
    name: ai-search-backend
    env: python
    rootDir: .
    buildCommand: |
      pip install -r requirements.txt
      python manage.py migrate
      python manage.py collectstatic --noinput
    startCommand: gunicorn backend.config.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: backend.config.settings
      - key: SERPAPI_KEY
        value: false
      - key: YOUTUBE_API_KEY
        value: false
      - key: DEBUG
        value: false
      - key: ALLOWED_HOSTS
        value: .onrender.com
      - key: CORS_ALLOWED_ORIGINS
        value: https://ai-search-tool.netlify.app
      - key: SECRET_KEY
        value: your-secret-key-here
      - key: USE_X_FORWARDED_HOST
        value: true
      - key: SECURE_PROXY_SSL_HEADER
        value: HTTP_X_FORWARDED_PROTO,https